### ISSUE TITLE
Can't create metrics when a single Cassandra server is down

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#134]
```
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console] 'Error from server: code=2200 [Invalid query] message="SERIAL is not supported as conditional update commit consistency. Use ANY if you mean "make sure it is accepted but I don\'t care how many replicas commit it for non-SERIAL reads""'
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console] Unhandled Error
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]         Traceback (most recent call last):
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/twisted/python/threadpool.py", line 191, in _worker
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             result = context.call(ctx, function, *args, **kwargs)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/twisted/python/context.py", line 118, in callWithContext
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/twisted/python/context.py", line 81, in callWithContext
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             return func(*args,**kw)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/lib/carbon/writer.py", line 145, in writeForever
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             writeCachedDataPoints()
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]         --- <exception caught here> ---
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/lib/carbon/writer.py", line 108, in writeCachedDataPoints
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             state.database.create(metric, archiveConfig, xFilesFactor, aggregationMethod)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/biggraphite/plugins/carbon.py", line 103, in create
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             self.cache().create_metric(metric)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/biggraphite/metadata_cache.py", line 138, in create_metric
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             self.__accessor.create_metric(metric)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 616, in create_metric
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             self._execute(statement, args)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 532, in _execute
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             result = self.__session.execute(*args, **kwargs)
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/cassandra/cluster.py", line 1998, in execute
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]           File "/opt/graphite/pypy/site-packages/cassandra/cluster.py", line 3781, in result
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]             raise self._final_exception
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console]         cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="SERIAL is not supported as conditional update commit consistency. Use ANY if you mean "make sure it is accepted but I don't care how many replicas commit it for non-SERIAL reads""
Sep 29 06:20:39 graphite-global-cache-bg05-am5 carbon-cache-0[15072]: [console] 'Error creating //biggraphite/cassandra:biggraphite/criteo....'
```

**Comment by iksaif** [comment]
Could be https://datastax-oss.atlassian.net/browse/JAVA-764 ?
This is weird because this statement should be using ONE.

**Comment by dpanth3r** [comment]
We are currently using LOCAL_QUORUM, I patched that some time ago.
These problems have appeared because we switched to LOCAL_QUORUM in the code but we still have RF=2 in the configuration: since it wants a *strict majority* of replicas to be available, losing one machine in RF=2 leaves you without any quorum (hence, RF=2 does not make any sense in quorum-based systems).

This is thus not a bug, but a feature :-)
