### ISSUE TITLE
Connections stale on mutations

### ISSUE THREAD

**Issue by erebe** [criteo/biggraphite#217]
When applying mutations, the connection to the cluster can stale due to the exception below. This is particularly annoying when using consistency higher than one (like the local_quorum) as when this append cassandra respond nothing to the client. 

This is related to this [issue](https://issues.apache.org/jira/browse/CASSANDRA-12928)
The problem is kind of hard to reproduce as there is no particular query or data configuration that trigger it

I have to spend some time on it to dig further

```
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: WARN  [TracingStage:1] 2016-12-22 08:30:08,632 AbstractLocalAwareExecutorService.java:167 - Uncaught exception on thread Thread[TracingStage:1,5,main]: {}
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: java.lang.AssertionError: null
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at io.netty.util.Recycler$WeakOrderQueue.<init>(Recycler.java:225) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:180) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at io.netty.util.Recycler.recycle(Recycler.java:141) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.utils.btree.BTree$Builder.recycle(BTree.java:839) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.utils.btree.BTree$Builder.build(BTree.java:1092) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.partitions.PartitionUpdate.build(PartitionUpdate.java:587) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.partitions.PartitionUpdate.maybeBuild(PartitionUpdate.java:577) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.partitions.PartitionUpdate.holder(PartitionUpdate.java:388) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:177) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:172) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.serialize(PartitionUpdate.java:779) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.Mutation$MutationSerializer.serialize(Mutation.java:389) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:249) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:581) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.Keyspace.applyNotDeferrable(Keyspace.java:440) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.Mutation.apply(Mutation.java:223) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.db.Mutation.apply(Mutation.java:237) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1416) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2640) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_91]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) ~[apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.concurrent.SEPExecutor.maybeExecuteImmediately(SEPExecutor.java:194) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy.performLocally(StorageProxy.java:1410) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy.sendToHintedEndpoints(StorageProxy.java:1317) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy$2.apply(StorageProxy.java:140) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy.performWrite(StorageProxy.java:1100) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.service.StorageProxy.mutate(StorageProxy.java:634) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.tracing.TraceStateImpl.mutateWithCatch(TraceStateImpl.java:122) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.tracing.TraceStateImpl$1.runMayThrow(TraceStateImpl.java:109) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) [apache-cassandra-3.10-af35eb6.jar:3.10-af35eb6]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [na:1.8.0_91]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
Dec 22 08:30:08 cstars07e01-par cassandra[15245]: at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

**Comment by erebe** [comment]
bumping to new version of io.netty seems to fix the problem
https://issues.apache.org/jira/browse/CASSANDRA-12928
