### ISSUE TITLE
How to I configure user + password in bgutil command?

### ISSUE THREAD

**Issue by betorvs** [criteo/biggraphite#283]
Hi All,

I try this:
```
# bgutil --cassandra_contact_points=cassandradb-1 --cassandra_keyspace=graphite syncdb
Traceback (most recent call last):
  File "/bin/bgutil", line 11, in <module>
    load_entry_point('biggraphite==0.8.6', 'console_scripts', 'bgutil')()
  File "/usr/lib/python2.7/site-packages/biggraphite/cli/bgutil.py", line 82, in main
    opts.func(accessor, opts)
  File "/usr/lib/python2.7/site-packages/biggraphite/cli/command_syncdb.py", line 36, in run
    schema = accessor.syncdb(dry_run=opts.dry_run)
  File "/usr/lib/python2.7/site-packages/biggraphite/drivers/cassandra.py", line 1667, in syncdb
    self._connect_clusters()
  File "/usr/lib/python2.7/site-packages/biggraphite/drivers/cassandra.py", line 938, in _connect_clusters
    self.contact_points_metadata, self.port_metadata)
  File "/usr/lib/python2.7/site-packages/biggraphite/drivers/cassandra.py", line 962, in _connect
    session = cluster.connect()
  File "cassandra/cluster.py", line 1152, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:17724)
  File "cassandra/cluster.py", line 1185, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:17545)
  File "cassandra/cluster.py", line 1172, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:17248)
  File "cassandra/cluster.py", line 2622, in cassandra.cluster.ControlConnection.connect (cassandra/cluster.c:47995)
  File "cassandra/cluster.py", line 2659, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:48892)
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'10.1.1.1': AuthenticationFailed('Remote end requires authentication.',)})
```

I cannot find any help in `bgutil --help`.

How to I configure **bgutil** command to support user+password to connect to cassandra server?

**Comment by iksaif** [comment]
Sorry for the delay, I didn't get the notification about this issue.
We actually never tried it with a user/password so there is currently no way to do it. 

You would have to change https://github.com/criteo/biggraphite/blob/master/biggraphite/drivers/cassandra.py to add the options, I can try to do it tomorrow but I may not have the time.

cc: @Thib17

**Comment by iksaif** [comment]
@betorvs  : https://github.com/criteo/biggraphite/pull/288 might work

**Comment by iksaif** [comment]
merged (install from HEAD, there will probably be a new release this month)
