### ISSUE TITLE
Scaling out Cassandra to greater than 1 node errors. Replication Factor 2

### ISSUE THREAD

**Issue by mfischer90** [criteo/biggraphite#292]
When trying to scale out cassandra, a few issues start popping up when using replication factor of 2. Is this a known issue? Some error messages:

`CassandraError: (u'Failed to glob: metrics on carbon.agents.*.cache.size', ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message=&#34;Operation timed out - received only 0 responses.&#34; info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'} info={\'received_responses\': None, \'required_responses\': None, \'consistency\': \'Not Set\'}',))&#10;&#10;</pre>&#10;</div>&#10;&#10;</center>&#10;`

`ERROR [MigrationStage:1] 2017-09-22 17:49:57,969 CassandraDaemon.java:228 - Exception in thread Thread[MigrationStage:1,5,main]
org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found ae0791e0-9fb8-11e7-9a43-addf67f43552; expected adfe1c00-9fb8-11e7-9a43-addf67f43552)`

**Comment by iksaif** [comment]
We use 20 nodes for data and 3 nodes for metadata, so it really should work.

Looks like one of your node is in a weird state (timing out, and having an incorrect schema). Since you have a RF=2, you should be able to shut it down, remove all the data, and rebuild it

**Comment by dpanth3r** [comment]
While this is not directly relevant to your issue, you should be careful with your RF settings: RF=2 does not  allow for quorum-based queries (which require a strict majority of replicas being available) in the event of a node failure. `LOCAL_QUORUM` is used by default for BigGraphite's background processing (repair missing data, cleanup, etc.).

**Comment by n-zeed** [comment]
any recomendations for the BigGraphite setup and RF=>1 to work? we are using:

# bgutil --cassandra_contact_points=${BG_CASSANDRA_CONTACT_POINTS} --cassandra_max_metrics_per_pattern=10000 syncdb

### local_settings.py
STORAGE_FINDERS = ['biggraphite.plugins.graphite.Finder']
BG_CASSANDRA_KEYSPACE = 'biggraphite'
BG_CASSANDRA_CONTACT_POINTS = os.getenv('BG_CASSANDRA_CONTACT_POINTS', '127.0.0.1')

### carbon.conf
DATABASE = biggraphite
BG_CASSANDRA_CONTACT_POINTS = xxxxxxxx.com
BG_CASSANDRA_KEYSPACE = biggraphite

### schemas.cql
CREATE KEYSPACE IF NOT EXISTS biggraphite_metadata WITH replication = {
  'class': 'SimpleStrategy',
  'replication_factor': '2'
} AND durable_writes = true;

CREATE KEYSPACE IF NOT EXISTS biggraphite WITH replication = {
  'class': 'SimpleStrategy',
  'replication_factor': '2'
} AND durable_writes = false;


or is the column mismatch error expected, we only get the glob error when receving lots of metrics

**Comment by deniszh** [comment]
Do not use '''class': 'SimpleStrategy', 'replication_factor': '2'" in production. 
Please use 'NetworkTopologyStrategy' and RF=3 - https://docs.datastax.com/en/cql/3.1/cql/cql_using/update_ks_rf_t.html

**Comment by n-zeed** [comment]
Thanks for the reply. So I followed your recommendation by running the following:
cqlsh> alter keyspace system_auth with replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': 3};
```nodetool repair```
```# cqlsh < /schema.cql
<stdin>:5:ConfigurationException: replication_factor is an option for SimpleStrategy, not NetworkTopologyStrategy
<stdin>:10:ConfigurationException: replication_factor is an option for SimpleStrategy, not NetworkTopologyStrategy```
so I set the schema file back to SimpleStragery with RF=3

I send the metrics to cassandra node 1 and get the table creation message, then the table initialization message and then the mismatch errors occur (below) the metrics do show up so just wondering if that error is expected or missing something else since I am new to cassandraDB.


```
INFO  [Native-Transport-Requests-1] 2017-09-29 20:38:10,168 MigrationManager.java:355 - Create new table: org.apache.cassandra.config.CFMetaData@47ac5d78[cfId=1b49c780-a556-11e7-8d2e-1b4101ce7101,ksName=biggraphite,cfName=datapoints_10080p_60s_0,flags=[COMPOUND],params=TableParams{comment={"row_size_ms": 120000000, "row_size": 2000, "schema_version": 0, "created_by": "biggraphite", "stage": "10080*60s_0"}, read_repair_chance=0.0, dclocal_read_repair_chance=0.1, bloom_filter_fp_chance=0.01, crc_check_chance=1.0, gc_grace_seconds=86400, default_time_to_live=605700, memtable_flush_period_in_ms=900000, min_index_interval=128, max_index_interval=2048, speculative_retry=99PERCENTILE, caching={'keys' : 'ALL', 'rows_per_partition' : 'NONE'}, compaction=CompactionParams{class=org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy, options={min_threshold=4, max_threshold=32, compaction_window_unit=HOURS, compaction_window_size=3, timestamp_resolution=MICROSECONDS}}, compression=org.apache.cassandra.schema.CompressionParams@3b71b39d, extensions={}, cdc=false},comparator=comparator(org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.ShortType)),partitionColumns=[[] | [value]],partitionKeyColumns=[metric, time_start_ms],clusteringColumns=[offset],keyValidator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.LongType),columnMetadata=[metric, value, offset, time_start_ms],droppedColumns={},triggers=[],indexes=[]]

INFO  [MigrationStage:1] 2017-09-29 20:38:10,239 ColumnFamilyStore.java:406 - Initializing biggraphite.datapoints_10080p_60s_0

ERROR [MigrationStage:1] 2017-09-29 20:38:10,252 CassandraDaemon.java:228 - Exception in thread Thread[MigrationStage:1,5,main]
org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found a6c37500-a555-11e7-b911-8d02fee0d46a; expected a6be6bf0-a555-11e7-b911-8d02fee0d46a)
        at org.apache.cassandra.config.CFMetaData.validateCompatibility(CFMetaData.java:808) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.config.CFMetaData.apply(CFMetaData.java:770) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.config.Schema.updateTable(Schema.java:621) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.updateKeyspace(SchemaKeyspace.java:1430) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.mergeSchema(SchemaKeyspace.java:1386) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.mergeSchemaAndAnnounceVersion(SchemaKeyspace.java:1336) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.MigrationManager$1.runMayThrow(MigrationManager.java:547) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81) [apache-cassandra-3.11.0.jar:3.11.0]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
ERROR [Native-Transport-Requests-1] 2017-09-29 20:38:10,253 QueryMessage.java:129 - Unexpected error during query
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found a6c37500-a555-11e7-b911-8d02fee0d46a; expected a6be6bf0-a555-11e7-b911-8d02fee0d46a)
        at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:401) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.MigrationManager.announce(MigrationManager.java:529) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:356) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:341) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:321) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.statements.CreateTableStatement.announceMigration(CreateTableStatement.java:89) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.statements.SchemaAlteringStatement.execute(SchemaAlteringStatement.java:93) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:217) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:248) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:233) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:517) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:410) [apache-cassandra-3.11.0.jar:3.11.0]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:35) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:348) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109) [apache-cassandra-3.11.0.jar:3.11.0]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found a6c37500-a555-11e7-b911-8d02fee0d46a; expected a6be6bf0-a555-11e7-b911-8d02fee0d46a)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_131]
        at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:397) ~[apache-cassandra-3.11.0.jar:3.11.0]
        ... 20 common frames omitted
Caused by: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found a6c37500-a555-11e7-b911-8d02fee0d46a; expected a6be6bf0-a555-11e7-b911-8d02fee0d46a)
        at org.apache.cassandra.config.CFMetaData.validateCompatibility(CFMetaData.java:808) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.config.CFMetaData.apply(CFMetaData.java:770) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.config.Schema.updateTable(Schema.java:621) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.updateKeyspace(SchemaKeyspace.java:1430) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.mergeSchema(SchemaKeyspace.java:1386) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.mergeSchemaAndAnnounceVersion(SchemaKeyspace.java:1336) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.MigrationManager$1.runMayThrow(MigrationManager.java:547) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81) ~[apache-cassandra-3.11.0.jar:3.11.0]
        ... 1 common frames omitted
```

**Comment by n-zeed** [comment]
apologies, I corrected the schemas files with:

```
$ cat configs/schema.cql
CREATE KEYSPACE IF NOT EXISTS biggraphite_metadata WITH replication = {
  'class': 'NetworkTopologyStrategy',
  'replication_factor': '3'
} AND durable_writes = true;

CREATE KEYSPACE IF NOT EXISTS biggraphite WITH replication = {
  'class': 'NetworkTopologyStrategy',
  'datacenter1': '3'
} AND durable_writes = false;
```

but still see the mismatch errors though

**Comment by iksaif** [comment]
How many carbon processes are you running in parallel ? I suspect that there is an issue because the table is being created by multiple clients at the same time. We might not have had this issue because we created the tables by hand earlier.

**Comment by deniszh** [comment]
Agreed with @iksaif - you need to create tables manually. Also, commands above will not touch existing data - you need to ALTER existing keyspaces.

**Comment by n-zeed** [comment]
Thanks guys! I will create all tables manually and continue with testing as far as the ALTER command I don't need right now since in test phase I am using docker images for cassandra:)

**Comment by iksaif** [comment]
I'm added a `--storage-schemas` flag to `bgutil syncdb` to pre-create tables in order to avoid this issue.
