### ISSUE TITLE
Crash from bad super call in DiskCache

### ISSUE THREAD

**Issue by Roguelazer** [criteo/biggraphite#336]
I'm evaluating BigGraphite (0.11.0 from pip) and have this repeating crash:

```
Traceback (most recent call last):
  File "biggraphite/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "biggraphite/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
  File "biggraphite/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "biggraphite/venv/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "biggraphite/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "biggraphite/venv/lib/python2.7/site-packages/biggraphite/plugins/carbon.py", line 244, in _background
    for metric in prometheus_client.REGISTRY.collect():
  File "biggraphite/venv/lib/python2.7/site-packages/prometheus_client/core.py", line 97, in collect
    for metric in collector.collect():
  File "biggraphite/venv/lib/python2.7/site-packages/prometheus_client/core.py", line 599, in collect
    for suffix, labels, value in collector._samples():
  File "biggraphite/venv/lib/python2.7/site-packages/prometheus_client/core.py", line 563, in _samples
    for suffix, sample_labels, value in metric._samples():
  File "biggraphite/venv/lib/python2.7/site-packages/prometheus_client/core.py", line 758, in samples
    return (('', {}, float(f())), )
  File "biggraphite/venv/lib/python2.7/site-packages/biggraphite/metadata_cache.py", line 95, in <lambda>
    self._size.set_function(lambda: self.stats()['size'])
  File "biggraphite/venv/lib/python2.7/site-packages/biggraphite/metadata_cache.py", line 526, in stats
    ret = super(MemoryCache, self).stat()
exceptions.TypeError: super(type, obj): obj must be an instance or subtype of type
```

This occurs in both Python 2.7 and Python 3.6 with both Carbon 1.0.2 and Carbon master.

Looking at the source, I'm pretty sure that the word `MemoryCache` on line 526 should read `DiskCache`

**Comment by iksaif** [comment]
Just fixed that in https://github.com/criteo/biggraphite/pull/334/commits/d082af99ac1dd9ff426ac6855632ea3ed9406d14

Current workaround would be to use the memory cache (to be honest, that's what we use in production)
