### ISSUE TITLE
split data and metadata between to Cassandra clusters

### ISSUE THREAD

**Issue by zerosoul13** [criteo/biggraphite#534]
Hello,

We've been using BigGraphite with Cassandra as a backend and up until now, performance had been great. We've run into slow queries on the Cassandra side and our DBA team asked if it would be possible to support 2 clusters so we split `biggraphite` and `biggraphite_metadata` amount 2 clusters.

## Environment setup

To avoid messing any environment, I am running containers like:

- 2 Cassandra containers (with different IPs as seen above) being as stand-alone servers
- 1 container running BigGraphite (1 carbon, 1 relay)

## Steps:

1. Setup BG with the following environment variables:

```    environment:
      - PYTHONPATH=/opt/graphite/lib/
      - CACHES=1
      - RELAYS=1
      - AGGREGATORS=0
      - CARBONLINK_HOSTS=127.0.0.1:7002:1
      - ALLOWED_HOSTS=*
      - SECRET_KEY=<edited>
      - BG_CASSANDRA_CONTACT_POINTS=172.28.1.5
      - BG_CASSANDRA_CONTACT_POINTS_METADATA=172.28.1.6
      - BG_CASSANDRA_USERNAME=cassandra
      - BG_CASSANDRA_PASSWORD=cassandra
```

2. Create `biggraphite` keyspace in data node (172.28.1.5)
3. Create `biggraphite` keyspace in metadata node (172.28.1.6)
4. Execute `bgutil` to sync database
```
/opt/graphite/bin/bgutil --data_driver=cassandra --cassandra_contact_points=172.28.1.5 --cassandra_username=cassandra --cassandra_password=cassandra  --metadata_driver=cassandra --cassandra_contact_points_metadata=172.28.1.6 syncdb --storage-schemas=/opt/graphite/conf/storage-schemas.conf
```
5. Wait for command to finish. Activity can be seen happening in `metadata` node and then on `data` node
6. from bg container execute: `curl localhost:8080/metrics/find?query=*`
```
(graphite) root@df5046a76b24:/# curl localhost:8080/metrics/find?query=*
[{"text": "carbon", "id": "carbon", "allowChildren": 1, "expandable": 1, "leaf": 0}, {"text": "collectd", "id": "collectd", "allowChildren": 1, "expandable": 1, "leaf": 0}]
```
7. Open Graphite web and try to open a metric:
```
carbon-cache_1  | InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace biggraphite_metadata does not exist"
carbon-cache_1  | 2019-09-06,02:54:25.821 :: Exception Caught
carbon-cache_1  | Traceback (most recent call last):
carbon-cache_1  |   File "/opt/graphite/webapp/graphite/metrics/views.py", line 128, in find_view
carbon-cache_1  |     leaves_only=leaves_only,
carbon-cache_1  |   File "/opt/graphite/webapp/graphite/storage.py", line 264, in find
carbon-cache_1  |     for match in self._find(query):
carbon-cache_1  |   File "/opt/graphite/webapp/graphite/storage.py", line 295, in _find
carbon-cache_1  |     for node in result or []:
carbon-cache_1  |   File "/opt/graphite/site-packages/biggraphite/plugins/graphite.py", line 375, in find_nodes
carbon-cache_1  |     results = self._find_glob(query, leaves_only, start_time, end_time)
carbon-cache_1  |   File "/opt/graphite/site-packages/biggraphite/plugins/graphite.py", line 413, in _find_glob
carbon-cache_1  |     self.accessor(),
carbon-cache_1  |   File "/opt/graphite/site-packages/biggraphite/plugins/graphite.py", line 299, in accessor
carbon-cache_1  |     raise e
```

## Question

Is it possible to support 2 Cassandra clusters so we can split the data just by updating our settings or are we expected to use ElasticSearch to support such feature?

**Comment by iksaif** [comment]
It's totally possible and that's how it was designed to run. I suggest you run the metadata on high-cpu+ssd machines and the other one on cheaper machines (but you can get more).

The only thing that you were missing is creating the `biggraphite_metadata` keyspace on both clusters (it might not be needed on the data one, but I think there was a bug that would require it)

**Comment by zerosoul13** [comment]
Thank you for such a prompt response. I've created `biggraphite_metadata` schema in data node and a new message pops-up

```
carbon-cache_1  | 2019-09-06,14:17:40.292 :: Exception encountered in <GET http://localhost:8080/metrics/find?query=*>
carbon-cache_1  | Traceback (most recent call last):
carbon-cache_1  |   File "/opt/graphite/site-packages/django/core/handlers/base.py", line 185, in _get_response
carbon-cache_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
carbon-cache_1  |   File "/opt/graphite/webapp/graphite/metrics/views.py", line 128, in find_view
carbon-cache_1  |     leaves_only=leaves_only,
carbon-cache_1  |   File "/opt/graphite/webapp/graphite/storage.py", line 264, in find
carbon-cache_1  |     for match in self._find(query):
carbon-cache_1  |   File "/opt/graphite/webapp/graphite/storage.py", line 295, in _find
carbon-cache_1  |     for node in result or []:
carbon-cache_1  |   File "/opt/graphite/site-packages/biggraphite/plugins/graphite.py", line 375, in find_nodes
carbon-cache_1  |     results = self._find_glob(query, leaves_only, start_time, end_time)
carbon-cache_1  |   File "/opt/graphite/site-packages/biggraphite/plugins/graphite.py", line 413, in _find_glob
carbon-cache_1  |     self.accessor(),
carbon-cache_1  |   File "/opt/graphite/site-packages/biggraphite/plugins/graphite.py", line 299, in accessor
carbon-cache_1  |     raise e
carbon-cache_1  | InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table metrics"
```

I've created both schemas `biggraphite` and `biggraphite_metadata` on both clusters but still no go. Any suggestions on how to solve this issue?

**Comment by zerosoul13** [comment]
The issue was fixed by manually creating `metrics`,  `metrics_metadata` and `directories` tables in `biggraphite_metadata` schema on data node.
